[package]
name = "binaries"
version = "0.1.0"
edition = "2024"

[dependencies]
# tism = { git = "https://github.com/cpspacesystems/tism", version = "0.1.0" }
tism = { path = "../../../temp/tism" }
zenoh = "1.9.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sim_tism_source"
path = "src/sim_tism_source.rs"

[[bin]]
name = "sim_zenoh_source"
path = "src/sim_zenoh_source.rs"
